### ISSUE TITLE
MTP

### ISSUE THREAD

**Issue by fiked** [ant9000/TWRP-protect#1]
Unfortunately, but the device does not disable MTP before entering the password.
As soon  connect the device to the computer, you can easily copy files. Can you fix it?

**Comment by ant9000** [comment]
Just go to Mount menu and disable MTP yourself; the configuration is persisted across reboot (it's a TWRP feature).

Antonio

**Comment by fiked** [comment]
Yes, it can be done. It would just be great if it was done automatically.
